#!/bin/bash

LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)

wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip

unzip chromedriver_linux64.zip && ln -s $PWD/chromedriver /usr/local/bin/chromedriver
